# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

modules_auth:
    resource: '../src/Modules/Auth/Controller/'
    type: attribute

modules_dashboard:
    resource: '../src/Modules/Dashboard/Controller/'
    type: attribute

modules_customers:
    resource: '../src/Modules/Customers/Controller/'
    type: attribute

modules_access:
    resource: '../src/Modules/Access/Controller/'
    type: attribute

modules_admin:
    resource: '../src/Modules/Admin/Controller/'
    type: attribute
