# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Shared kernel
    App\Shared\:
        resource: '../src/Shared/'

    # Auth — brak własnych encji, używa User z modułu Admin
    App\Modules\Auth\:
        resource: '../src/Modules/Auth/'
        exclude:
            - '../src/Modules/Auth/DTO/'

    # Dashboard
    App\Modules\Dashboard\:
        resource: '../src/Modules/Dashboard/'
        exclude:
            - '../src/Modules/Dashboard/DTO/'

    # Customers
    App\Modules\Customers\:
        resource: '../src/Modules/Customers/'
        exclude:
            - '../src/Modules/Customers/Entity/'
            - '../src/Modules/Customers/DTO/'

    # Access (Role)
    App\Modules\Access\:
        resource: '../src/Modules/Access/'
        exclude:
            - '../src/Modules/Access/Entity/'
            - '../src/Modules/Access/DTO/'

    # Admin (User)
    App\Modules\Admin\:
        resource: '../src/Modules/Admin/'
        exclude:
            - '../src/Modules/Admin/Entity/'
            - '../src/Modules/Admin/DTO/'
